
insert into categoria (id, nombre) values (NEXTVAL('hibernate_sequence'), 'Comida');
insert into categoria (id, nombre) values (NEXTVAL('hibernate_sequence'), 'Bebida');
insert into categoria (id, nombre) values (NEXTVAL('hibernate_sequence'), 'Complementos');

insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Juice - Orange, Concentrate', 91, 2, 'http://dummyimage.com/139x103.bmp/5fa2dd/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Beef - Ground, Extra Lean, Fresh', 87, 1, 'http://dummyimage.com/206x125.bmp/cc0000/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Cheese - Parmesan Grated', 39, 1, 'http://dummyimage.com/133x134.bmp/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Cups 10oz Trans', 67, 1, 'http://dummyimage.com/245x246.jpg/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Wine - Beringer Founders Estate', 27, 2, 'http://dummyimage.com/139x103.bmp/5fa2dd/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Bread - Wheat Baguette', 82, 2, 'http://dummyimage.com/206x125.bmp/cc0000/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Quail - Eggs, Fresh', 3, 2, 'http://dummyimage.com/133x134.bmp/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Cheese - Mascarpone', 97, 2, 'http://dummyimage.com/245x246.jpg/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Mace', 25, 2, 'http://dummyimage.com/139x103.bmp/5fa2dd/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Oil - Shortening - All - Purpose', 63, 2, 'http://dummyimage.com/206x125.bmp/cc0000/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Marjoram - Fresh', 60, 2, 'http://dummyimage.com/133x134.bmp/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Turnip - White', 74, 2, 'http://dummyimage.com/245x246.jpg/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Pork Salted Bellies', 38, 2, 'http://dummyimage.com/139x103.bmp/5fa2dd/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Longos - Greek Salad', 15, 2, 'http://dummyimage.com/206x125.bmp/cc0000/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Amaretto', 85, 2, 'http://dummyimage.com/133x134.bmp/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Godiva White Chocolate', 97, 2, 'http://dummyimage.com/245x246.jpg/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Tomatoes - Roma', 61, 2, 'http://dummyimage.com/139x103.bmp/5fa2dd/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Oven Mitt - 13 Inch', 1, 3, 'http://dummyimage.com/206x125.bmp/cc0000/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Vermouth - White, Cinzano', 72, 2, 'http://dummyimage.com/133x134.bmp/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Club Soda - Schweppes, 355 Ml', 38, 2, 'http://dummyimage.com/245x246.jpg/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Fenngreek Seed', 1, 1, 'http://dummyimage.com/139x103.bmp/5fa2dd/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Dill Weed - Dry', 72, 1, 'http://dummyimage.com/206x125.bmp/cc0000/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Pepper - Green', 56, 1, 'http://dummyimage.com/133x134.bmp/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Bacardi Breezer - Tropical', 35, 2, 'http://dummyimage.com/245x246.jpg/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Wine - Merlot Vina Carmen', 14, 2, 'http://dummyimage.com/139x103.bmp/5fa2dd/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Sauce - Black Current, Dry Mix', 9, 1, 'http://dummyimage.com/206x125.bmp/cc0000/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Crab - Soft Shell', 17, 1, 'http://dummyimage.com/133x134.bmp/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Jameson Irish Whiskey', 19, 2, 'http://dummyimage.com/245x246.jpg/dddddd/000000');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Muffin Chocolate Individual Wrap', 77, 1, 'http://dummyimage.com/139x103.bmp/5fa2dd/ffffff');
insert into producto (id, nombre, precio, categoria_id, imagen) values (NEXTVAL('hibernate_sequence'), 'Mussels - Frozen', 95, 1, 'http://dummyimage.com/206x125.bmp/cc0000/ffffff');
